spring.application.name=first-spring
server.port=8080

# PostgreSQL connection and driver
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel
spring.datasource.username=postgres
spring.datasource.password=paulius123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA table creation, debug, postgresql dialect choose
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Tells Spring Boot Actuator to expose all available endpoints over HTTP
management.endpoints.web.exposure.include=*
management.info.env.enabled
management.info.build.enabled
management.info.git.enabled
management.info.java.enabled
management.info.os.enabled
